name: bocekilaclama
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.3
  get: ^4.6.5
  crypto: ^3.0.2
  flutter_svg: ^2.0.5
  dart_des: ^1.0.2
  flutter_screenutil: ^5.9.0
  lottie: ^2.3.2
  carousel_slider: ^4.2.1
  geolocator: ^9.0.2
  flutter_polyline_points: ^2.0.0
  dio: ^5.2.1+1
  http: ^1.2.1
  intl: ^0.18.1
  http_parser: ^4.0.2
  image_picker: ^1.0.2
  path: ^1.8.3
  path_provider: ^2.0.15
  cached_network_image: ^3.3.1
  animated_notch_bottom_bar: ^1.0.3
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  geocoding: ^3.0.0
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/animations/

  fonts:
    - family: MontserratBlack
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Black.ttf
    - family: MontserratExtraBold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ExtraBold.ttf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
    - family: MontserratSemiBold
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-SemiBold.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
    - family: MontserratThin
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
    - family: MontserratLight
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
    - family: MontserratExtraLight
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-ExtraLight.ttf
